name: PaperEdu
version: '${version}'
main: org.blog.paperedu.PaperEdu
api-version: '1.20'
commands:
  uinfo:
   description: display player data
  getGun:
    description: get custom gun
  getBullet:
    description: get custom gun bullet